namespace Supernova.Enum.Generators;

public static class SourceGeneratorHelper
{
    private const string Header = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Supernova source generator
//     Do not change this file !!
// </auto-generated>
//------------------------------------------------------------------------------
using System;
";

    public const string NameSpace = "EnumFastToStringGenerated";
    public const string AttributeName = "EnumGenerator";
    public const string ExtensionMethodName = "StringToFast";

    public const string Attribute = Header + $@"

namespace {NameSpace};

[AttributeUsage(AttributeTargets.Enum)]
public sealed class {AttributeName}Attribute : System.Attribute
{{
}}";
}
