name: .NET Core

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
            dotnet-version: '8.0.102'

      - name: Install Dependencies
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Test (Release)
        run: dotnet test --configuration Release --no-build --no-restore

      - name: Pack (Release)
        run: dotnet pack --configuration Release --output .\nuget --no-build --no-restore

      - name: Publish
        if: github.event_name == 'push'
        run: |
            if ( "${{github.ref}}" -match "^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$" ) {
                dotnet nuget push .\nuget\*.nupkg -s nuget.org -k ${{secrets.NUGET_TOKEN}} --skip-duplicate
            } else {
                echo "publish is only enabled by tagging with a release tag"
            }
